<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable implements MustVerifyEmail
{
    use HasFactory;
    use Notifiable;

    const ROLE_ADMIN = 'admin';

    const ROLE_STAFF = 'staff';

    const ROLE_PROJECT_MANAGER = 'project_manager';

    const ROLE_RGMO_HEAD = 'rgmo_head';

    const STATUS_ACTIVE = 'active';

    const STATUS_INACTIVE = 'inactive';

    const STATUS_SUSPENDED = 'suspended';

    public const SIDEBAR_ITEMS = [
        'dashboard',
        'health',
        'inventory',
        'projects',
        'notifications',
        'requests',
        'reports',
        'forecasting',
        'users',
        'system',
    ];

    protected $fillable = [
        'name',
        'email',
        'password',
        'role',
        'department',
        'status',
        'avatar',
        'sidebar_order',
        'last_login_at',
        'login_attempts',
        'locked_until',
        'two_factor_enabled',
        'two_factor_secret',
        'two_factor_recovery_codes',
        'two_factor_last_used_step',
    ];

    protected $hidden = [
        'password',
        'remember_token',
        'two_factor_secret',
        'two_factor_recovery_codes',
    ];

    /**
     * Roles supported by the application.
     *
     * @return array<int, string>
     */
    public static function availableRoles(): array
    {
        return [
            self::ROLE_ADMIN,
            self::ROLE_STAFF,
            self::ROLE_PROJECT_MANAGER,
            self::ROLE_RGMO_HEAD,
        ];
    }

    /**
     * Resolve the stored role into its canonical RBAC role name.
     */
    public function normalizedRole(): string
    {
        if (! is_string($this->role) || $this->role === '') {
            return self::ROLE_STAFF;
        }

        return $this->role;
    }

    /**
     * Determine whether the user has one of the given roles.
     *
     * @param  string|array<int, string>  $roles
     */
    public function hasRole(string|array $roles): bool
    {
        $roles = (array) $roles;

        return in_array($this->normalizedRole(), $roles, true);
    }

    /**
     * Determine whether the user can perform a named permission.
     *
     * @param  string|array<int, string>  $permissions
     */
    public function hasPermission(string|array $permissions): bool
    {
        if ($this->isAdmin()) {
            return true;
        }

        $permissions = (array) $permissions;
        $rolePermissions = config('rbac.roles.'.$this->normalizedRole().'.permissions', []);

        return count(array_intersect($permissions, $rolePermissions)) > 0;
    }

    /**
     * Get the attributes that should be cast.
     */
    protected function casts(): array
    {
        return [
            'email_verified_at' => 'datetime',
            'password' => 'hashed',
            'last_login_at' => 'datetime',
            'locked_until' => 'datetime',
            'sidebar_order' => 'array',
            'two_factor_enabled' => 'boolean',
            'two_factor_secret' => 'encrypted',
            'two_factor_recovery_codes' => 'encrypted:array',
            'two_factor_last_used_step' => 'integer',
        ];
    }

    // Relationships
    /**
     * Get all resource requests submitted by this user.
     */
    public function requests(): HasMany
    {
        return $this->hasMany(ResourceRequest::class);
    }

    /**
     * Get all activity logs recorded for this user.
     */
    public function activityLogs(): HasMany
    {
        return $this->hasMany(UserActivityLog::class);
    }

    /**
     * Get all audit logs generated by this user's actions.
     */
    public function auditLogs(): HasMany
    {
        return $this->hasMany(AuditLog::class);
    }

    /**
     * Get all login history records for this user.
     */
    public function loginHistories(): HasMany
    {
        return $this->hasMany(LoginHistory::class);
    }

    /**
     * Get all notifications sent to this user.
     */
    public function notifications(): HasMany
    {
        return $this->hasMany(Notification::class);
    }

    /**
     * Handle managed projects.
     */
    public function managedProjects(): BelongsToMany
    {
        return $this->belongsToMany(Project::class)->withTimestamps();
    }

    // Scopes
    /**
     * Scope a query to only include active users.
     */
    public function scopeActive(Builder $query): Builder
    {
        return $query->where('status', self::STATUS_ACTIVE);
    }

    /**
     * Scope a query to only include inactive users.
     */
    public function scopeInactive(Builder $query): Builder
    {
        return $query->where('status', self::STATUS_INACTIVE);
    }

    /**
     * Scope a query to only include suspended users.
     */
    public function scopeSuspended(Builder $query): Builder
    {
        return $query->where('status', self::STATUS_SUSPENDED);
    }

    /**
     * Scope a query to only include users with the admin role.
     */
    public function scopeAdmin(Builder $query): Builder
    {
        return $query->where('role', self::ROLE_ADMIN);
    }

    /**
     * Scope a query to only include users with the staff role.
     */
    public function scopeStaff(Builder $query): Builder
    {
        return $query->where('role', self::ROLE_STAFF);
    }

    /**
     * Scope a query to only include project manager users.
     */
    public function scopeProjectManager(Builder $query): Builder
    {
        return $query->where('role', self::ROLE_PROJECT_MANAGER);
    }

    /**
     * Scope a query to only include RGMO Head users.
     */
    public function scopeRgmoHead(Builder $query): Builder
    {
        return $query->where('role', self::ROLE_RGMO_HEAD);
    }

    // Methods
    /**
     * Check if the user has the administrator role.
     */
    public function isAdmin(): bool
    {
        return $this->role === self::ROLE_ADMIN;
    }

    /**
     * Check if the user has the staff role.
     */
    public function isStaff(): bool
    {
        return $this->role === self::ROLE_STAFF;
    }

    /**
     * Check if the user has the project manager role.
     */
    public function isProjectManager(): bool
    {
        return $this->role === self::ROLE_PROJECT_MANAGER;
    }

    /**
     * Check if the user has the RGMO head role.
     */
    public function isRgmoHead(): bool
    {
        return $this->role === self::ROLE_RGMO_HEAD;
    }

    /**
     * Check if the user's account status is active.
     */
    public function isActive(): bool
    {
        return $this->status === self::STATUS_ACTIVE;
    }

    /**
     * Check if the user's account has been suspended.
     */
    public function isSuspended(): bool
    {
        return $this->status === self::STATUS_SUSPENDED;
    }

    /**
     * Check if the user's account is currently locked due to too many login attempts.
     */
    public function isAccountLocked(): bool
    {
        return $this->locked_until && $this->locked_until->isFuture();
    }

    /**
     * Increment the number of failed login attempts and lock the account if threshold is reached.
     */
    public function incrementLoginAttempts(): void
    {
        $this->increment('login_attempts');

        if ($this->login_attempts >= 5) {
            $this->update(['locked_until' => now()->addMinutes(15)]);
        }
    }

    /**
     * Reset the failed login attempts counter and clear any account lock.
     */
    public function resetLoginAttempts(): void
    {
        $this->update(['login_attempts' => 0, 'locked_until' => null]);
    }
}
