<?php

return [
    'roles' => [
        'admin' => [
            'label' => 'Administrator',
            'permissions' => [
                'manage-users',
                'assign-roles',
                'manage-inventory',
                'view-inventory',
                'submit-request',
                'update-pending-request',
                'review-request',
                'approve-request',
                'record-withdrawal',
                'record-utilization',
                'monitor-status',
                'view-history',
                'generate-reports',
                'view-forecasts',
                'view-audit-trail',
                'manage-forecasting-settings',
                'receive-notifications',
            ],
        ],
        'staff' => [
            'label' => 'Staff',
            'permissions' => [
                'view-inventory',
                'submit-request',
                'update-pending-request',
                'record-utilization',
                'monitor-status',
                'view-history',
                'receive-notifications',
            ],
        ],
        'project_manager' => [
            'label' => 'Project Manager',
            'permissions' => [
                'view-inventory',
                'submit-request',
                'update-pending-request',
                'review-request',
                'record-withdrawal',
                'record-utilization',
                'monitor-status',
                'view-history',
                'generate-reports',
                'view-forecasts',
                'receive-notifications',
            ],
        ],
        'rgmo_head' => [
            'label' => 'RGMO Head',
            'permissions' => [
                'manage-inventory',
                'view-inventory',
                'review-request',
                'approve-request',
                'record-withdrawal',
                'monitor-status',
                'view-history',
                'generate-reports',
                'view-forecasts',
                'view-audit-trail',
                'receive-notifications',
            ],
        ],
        'field_personnel' => [
            'label' => 'Project Manager',
            'alias_of' => 'project_manager',
            'permissions' => [
                'view-inventory',
                'submit-request',
                'update-pending-request',
                'review-request',
                'record-withdrawal',
                'record-utilization',
                'monitor-status',
                'view-history',
                'generate-reports',
                'view-forecasts',
                'receive-notifications',
            ],
        ],
    ],

    'permissions' => [
        'manage-users' => 'Manage users',
        'assign-roles' => 'Assign roles and permissions',
        'manage-inventory' => 'Manage inventory records',
        'view-inventory' => 'View inventory availability',
        'submit-request' => 'Submit resource requests',
        'update-pending-request' => 'Update or cancel pending requests',
        'review-request' => 'Review resource requests',
        'approve-request' => 'Approve or reject requests',
        'record-withdrawal' => 'Record item withdrawals',
        'record-utilization' => 'Record resource utilization',
        'monitor-status' => 'Monitor request status',
        'view-history' => 'View request history',
        'generate-reports' => 'Generate reports',
        'view-forecasts' => 'View forecasting results',
        'view-audit-trail' => 'View audit trail',
        'manage-forecasting-settings' => 'Manage forecasting settings',
        'receive-notifications' => 'Receive notifications',
    ],
];